name: anomaly_detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - opencv
  - albumentations
  - tqdm
  - pyyaml
  - hydra-core
  - tensorboard
  - jupyter
  - pip
  - pip:
      - torch==2.2.1+cu126
      - torchvision==0.17.1+cu126
      - torchaudio==2.2.1+cu126
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torchmetrics
      - einops
      - diffusers
      - transformers